version: "3"
services:
  app:
    build: .
    image: 35.153.93.153:8081/repository/dockerrepo:latest
    container_name: dev_access_mgnt
    restart: always
    ports:
      - "8090:8090"
    stdin_open: true
    tty: true
